[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "static"

[build]
  publish = ".output/public"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
